### ISSUE TITLE
Error with the current setup?

### ISSUE THREAD

**Issue by raRaRa** [JazzyGrim/dotfiles#5]
Hey Sindo! First of all I really appreciate all your videos, they've given me inspiration to give Neovim another try, after many previous failures.

I just finished cloning your dot files and replacing mine (I basically removed everything I had before and backed it up), since I really like the look and feel of your setup.

When I start writing some code in a large React file I get bunch of errors relating to inlayhint like these below. Any clue what the issue could be? It usually happens when I create a new line.

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/c8cfd156-5ce9-4289-bf9c-eb8d2795eaf5">

**Comment by stuff97** [comment]
Hi @raRaRa , 

Seems like the config is quite a bit old now and needs an update to work correctly,
